### ISSUE TITLE
Repository abandoned?

### ISSUE THREAD

**Issue by m-mohr** [chronotruck/vue-ctk-date-time-picker#199]
It seems like this repository is abandoned. The author of the package is not working for @chronotruck any longer and wasn't active on GitHub for quite some time now. Very unfortunate, because it's the best Vue date/time picker, I think.  How to proceed?

**Comment by WilliamDASILVA** [comment]
Hello sir,

Thank you for your issue.
Indeed the last developer leaves the organization and we needed some time to make the transition.
The package **will remain maintained** since it's mainly used by Chronotruck in its projects.

Pull-requests are very welcomed.
In the name of @loicmazel and Chronotruck, thank you for your kind words.

Have a great day!
