### ISSUE TITLE
Last 7 days and last 30 days

### ISSUE THREAD

**Issue by Paul-Cl-ark** [chronotruck/vue-ctk-date-time-picker#232]
`Last 7 days` range shortcut selects 8 days, and the `Last 30 days` shortcut selects 31 days.

Not sure if this is intended but it seems odd. 

Currently using `:custom-shortcuts="shortcuts"`
```
shortcuts: [
      { label: 'This Week', value: 'week' },
      { label: 'Last Week', value: '-week' },
      { label: 'Last 7 days', value: 6 },
      { label: 'Last 30 days', value: 29 },
      { label: 'This Month', value: 'month' },
      { label: 'Last Month', value: '-month' },
      { label: 'This Year', value: 'year' },
      { label: 'Last Year', value: '-year' }
    ]
```

as a workaround.

**Comment by WilliamDASILVA** [comment]
Hello!

There is already an issue about that https://github.com/chronotruck/vue-ctk-date-time-picker/issues/210
Yet that's something debatable because not everyone agrees on the same definition of "last x days". In the meantime, your solution works.

You could even use the new value-function method for more complexe values.
```js
[
  {
    key: 'customValue',
    label: 'My custom thing',
    value: () => {
      return {
        start: moment(),
        end: moment().add(2, 'days')
      }
    }
  },
];
```
