### ISSUE TITLE
pick year

### ISSUE THREAD

**Issue by jasminBnology** [chronotruck/vue-ctk-date-time-picker#286]
when you set min date and the year is not in the 'screen' range you need to choose the first 'smallest' year and then set again a new year and the range changes.

1.clicked on year '2020'.
2.want to set my birthday.
3.in the range there are only 7 years forward and back.
4.i cant roll farther/back years
5.click on 2013
6.click again on the chosen year and then step 2 all over again. 

you need to add some option to choose farther years.

**Comment by erubielgzz** [comment]
Had the same problem, by now you could use this code, but you would have to make and use your own version of this repo.

#264 

Download from master branch in here
Create project on your local dev
npm install
Search for the file I mention on the issue and replace the code on the issue
npm run build
use the dist files instead of installing via npm

You should end with something similar to this (but in english):
<img width="433" alt="Screen Shot 2020-04-13 at 7 07 41" src="https://user-images.githubusercontent.com/3204663/79119345-bf18ff00-7d55-11ea-8016-492cbe32a078.png">
